// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tansiqy.DAL.Database;

#nullable disable

namespace Tansiqy.DAL.Migrations
{
    [DbContext(typeof(TansiqyContext))]
    [Migration("20250509165534_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tansiqy.DAL.Models.Degree", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.DegreeDepartment", b =>
                {
                    b.Property<int>("DegID")
                        .HasColumnType("int");

                    b.Property<int>("DepID")
                        .HasColumnType("int");

                    b.Property<int>("DegreeID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.HasKey("DegID", "DepID");

                    b.HasIndex("DegreeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("DegreeDepartments");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("faculty_Id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("faculty_Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.Faculty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.FacultyDegree", b =>
                {
                    b.Property<int>("FID")
                        .HasColumnType("int");

                    b.Property<int>("DegID")
                        .HasColumnType("int");

                    b.Property<int>("DegreeID")
                        .HasColumnType("int");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.HasKey("FID", "DegID");

                    b.HasIndex("DegreeID");

                    b.HasIndex("FacultyID");

                    b.ToTable("FacultyDegrees");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.FacultyFavourite", b =>
                {
                    b.Property<int>("FID")
                        .HasColumnType("int");

                    b.Property<int>("FavID")
                        .HasColumnType("int");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<int>("FavouriteID")
                        .HasColumnType("int");

                    b.HasKey("FID", "FavID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("FavouriteID");

                    b.ToTable("FacultyFavourites");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.FacultyUniversity", b =>
                {
                    b.Property<int>("FID")
                        .HasColumnType("int");

                    b.Property<int>("UniID")
                        .HasColumnType("int");

                    b.Property<int>("FacultyID")
                        .HasColumnType("int");

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("FID", "UniID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("UniversityID");

                    b.ToTable("FacultyUniversities");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.Favourite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.University", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.UniversityDepartment", b =>
                {
                    b.Property<int>("UniID")
                        .HasColumnType("int");

                    b.Property<int>("DepID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("UniID", "DepID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("UniversityID");

                    b.ToTable("UniversityDepartments");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Degree_Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Degree_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.DegreeDepartment", b =>
                {
                    b.HasOne("Tansiqy.DAL.Models.Degree", "Degree")
                        .WithMany("DegreeDepartments")
                        .HasForeignKey("DegreeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tansiqy.DAL.Models.Department", "Department")
                        .WithMany("DegreeDepartments")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.Department", b =>
                {
                    b.HasOne("Tansiqy.DAL.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("faculty_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.FacultyDegree", b =>
                {
                    b.HasOne("Tansiqy.DAL.Models.Degree", "Degree")
                        .WithMany("FacultyDegrees")
                        .HasForeignKey("DegreeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tansiqy.DAL.Models.Faculty", "Faculty")
                        .WithMany("FacultyDegrees")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.FacultyFavourite", b =>
                {
                    b.HasOne("Tansiqy.DAL.Models.Faculty", "Faculty")
                        .WithMany("FacultyFavourites")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tansiqy.DAL.Models.Favourite", "Favourite")
                        .WithMany("FacultyFavourites")
                        .HasForeignKey("FavouriteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Favourite");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.FacultyUniversity", b =>
                {
                    b.HasOne("Tansiqy.DAL.Models.Faculty", "Faculty")
                        .WithMany("FacultyUniversities")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tansiqy.DAL.Models.University", "University")
                        .WithMany("FacultyUniversities")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.UniversityDepartment", b =>
                {
                    b.HasOne("Tansiqy.DAL.Models.Department", "Department")
                        .WithMany("UniversityDepartments")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tansiqy.DAL.Models.University", "University")
                        .WithMany("UniversityDepartments")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.User", b =>
                {
                    b.HasOne("Tansiqy.DAL.Models.Degree", "Degree")
                        .WithMany("Users")
                        .HasForeignKey("Degree_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.Degree", b =>
                {
                    b.Navigation("DegreeDepartments");

                    b.Navigation("FacultyDegrees");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.Department", b =>
                {
                    b.Navigation("DegreeDepartments");

                    b.Navigation("UniversityDepartments");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("FacultyDegrees");

                    b.Navigation("FacultyFavourites");

                    b.Navigation("FacultyUniversities");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.Favourite", b =>
                {
                    b.Navigation("FacultyFavourites");
                });

            modelBuilder.Entity("Tansiqy.DAL.Models.University", b =>
                {
                    b.Navigation("FacultyUniversities");

                    b.Navigation("UniversityDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
